management:
    endpoint:
        health:
            enabled: true
            show-details: always
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: metrics, health
    metrics:
        distribution:
            maximum-expected-value:
                http:
                    server:
                        requests: 1000
            percentiles-histogram:
                http:
                    server:
                        requests: true
        enable:
            jvm: false
search:
    google: https://www.googleapis.com/books/v1/volumes?q=
    googleApikey: AIzaSyAyX5cUuVvHRto_bNFYfkqQt3doYhe0RnE
    itune: https://itunes.apple.com/search?
    limit: 5
server:
    port: 8080
spring:
    application:
        name: senior-test
    data:
        redis:
            host: localhost
            password: admin
            port: 6379
    cache:
      redis:
          time-to-live: 1000s

